# See also dependencies in ../.tool-versions
[tools]
node = "22.14.0"
python = "3.10.2"

# For linting documentation
markdownlint-cli2 = "0.22.1"
lychee = "0.24.2"
vale = "3.14.1"

[env]
'_'.path = ["{{config_root}}/node_modules/.bin"]
